<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2016
* @Version	 : 1.0
*/

function Admin_menu() {
	
	$items["admin/admincp"] = array(
        "title" => t("CMS"),
        "description" => t("Administration"),
        'page callback' => 'admin_redirect',
        'access callback' => TRUE,
        'type' => MENU_NORMAL_ITEM,
    );
	$items["admincp"] = array(
        "title" => t("CMS"),
        "description" => t("Administration"),
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/type"] = array(
        "title" => t('Type'),
        "description" => "Type",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/category"] = array(
        "title" => t('Category'),
        "description" => "Category",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/document"] = array(
        "title" => t('Document'),
        "description" => "Document",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items["admincp/news"] = array(
        "title" => t('News'),
        "description" => "News",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/comments"] = array(
        "title" => t('comments'),
        "description" => "comments",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
     $items["admincp/video"] = array(
        "title" => t('Video'),
        "description" => "banner",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

    $items["admincp/configinfo"] = array(
        "title" => t('Config info'),
        "description" => "Config info",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

	$items["admincp/supportonline"] = array(
		"title" => t('Support online'),
		"description" => "Support online",
		'page callback' => 'router_page',
		'access callback' => TRUE,
		'type' => MENU_CALLBACK,
	);
    $items["admincp/banner"] = array(
        "title" => t('Banner ads'),
        "description" => "banner",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
    $items["admincp/slideimage"] = array(
        "title" => t('Slide image'),
        "description" => "banner",
        'page callback' => 'router_page',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );

  return $items;
}

function Admin_block_info() {

    $blocks['admin-header'] = array(
        'info' => t('Block admin header'),
        'status'	=> TRUE,
        'region'	=> 'header',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-left'] = array(
        'info' => t('Block admin left'),
        'status'	=> TRUE,
        'region'	=> 'left',
        'weight'	=> 0,
        'visibility' => 1,
    );

	 $blocks['admin-content'] = array(
        'info' => t('Block admin content'),
        'status'	=> TRUE,
        'region'	=> 'content',
        'weight'	=> 0,
        'visibility' => 1,
    );

    $blocks['admin-footer'] = array(
        'info' => t('Block admin footer'),
        'status'	=> TRUE,
        'region'	=> 'footer',
        'weight'	=> 0,
        'visibility' => 1,
    );

    return $blocks;
}

function Admin_block_view($delta='') {
    $block = array();
    switch ($delta) {
        case 'admin-header':
            $block['subject'] = t('Block admin header');
            $block['content'] = blockAdminHeader();
            break;

		case 'admin-left':
            $block['subject'] = t('Block admin left');
            $block['content'] = blockAdminLeft();
            break;

        case 'admin-content':
            $block['subject'] = t('Block admin content');
            $block['content'] = blockAdminContent();
            break;

        case 'admin-footer':
            $block['subject'] = t('Block admin footer');
            $block['content'] = blockAdminFooter();
            break;
    }

    return $block;
}

function Admin_theme() {
    return array(
        //Block
        'admin-header' 	=> array('template' 	=> 'View/tpl/block/admin-header'),
        'admin-left' 	=> array( 'template' 	=> 'View/tpl/block/admin-left'),
      	'admin-content' => array('template' 	=> 'View/tpl/block/admin-content'),
        'admin-footer' 	=> array('template' 	=> 'View/tpl/block/admin-footer'),

        //Type
        'indexType'         => array('template' => 'View/tpl/type/indexType'),
        'addType'           => array('template' => 'View/tpl/type/addType'),

        //Category
        'indexCategory'         => array('template' => 'View/tpl/category/indexCategory'),
        'addCategory'           => array('template' => 'View/tpl/category/addCategory'),

        //document
        'indexDocument'         => array('template' => 'View/tpl/document/indexDocument'),
        'addDocument'           => array('template' => 'View/tpl/document/addDocument'),

        //lien he
        'indexComments' 		=> array('template' => 'View/tpl/comments/indexComments'),
        'addComments' 		=> array('template' => 'View/tpl/comments/addComments'),

        //News
        'indexNews'         => array('template' => 'View/tpl/news/indexNews'),
        'addNews'           => array('template' => 'View/tpl/news/addNews'),

        //SlideImage
        'indexSlideImage'         => array('template' => 'View/tpl/slideimage/indexSlideImage'),
        'addSlideImage'           => array('template' => 'View/tpl/slideimage/addSlideImage'),

        //ConfigInfo
        'indexConfigInfo'       => array('template' => 'View/tpl/configInfo/indexConfigInfo'),
        'addConfigInfo'         => array('template' => 'View/tpl/configInfo/addConfigInfo'),

        //SupportOnline
        'indexSupportOnline'    => array('template' => 'View/tpl/supportOnline/indexSupportOnline'),
        'addSupportOnline'      => array('template' => 'View/tpl/supportOnline/addSupportOnline'),

        //Banner
        'indexBanner'       => array('template' => 'View/tpl/banner/indexBanner'),
        'addBanner'         => array('template' => 'View/tpl/banner/addBanner'),

        //Video
        'indexVideo'        => array('template' => 'View/tpl/video/indexVideo'),
        'addVideo'      => array('template' => 'View/tpl/video/addVideo'), 
    );
}

function Admin_permission() {
  return array(
    'access protected Admin' => array(
      'title' => t('access protected Admin'),
    ),
  );
}

function Admin_init(){
	
	$files = array(
        //Block
		'Controller/BlockController.php',
        //Type
        'Model/Type.php',
        'Controller/TypeController.php',
        //Category
        'Model/Category.php',
        'Controller/CategoryController.php',

        //Category
        'Model/Document.php',
        'Controller/DocumentController.php',

        //Comments
        'Model/Comments.php',
        'Controller/CommentsController.php',

        //News
        'Model/News.php',
        'Controller/NewsController.php',

        //News
        'Model/SlideImage.php',
        'Controller/SlideImageController.php',

        //ConfigInfo
        'Model/ConfigInfo.php',
        'Controller/ConfigInfoController.php',

		//SupportOnline
		'Model/SupportOnline.php',
		'Controller/SupportOnlineController.php',

        //Banner
        'Model/Banner.php',
        'Controller/BannerController.php',

		//Video
        'Model/Video.php',
        'Controller/VideoController.php',  
	);
	Loader::load('Admin', $files);
}