<?php
/*
* @Created by: HSS
* @Author	 : nguyenduypt86@gmail.com
* @Date 	 : 06/2016
* @Version	 : 1.0
*/
function Site_menu() {
 
	$items['trang-chu.html'] = array(
        'title' => t('Trang chủ'),
        'page callback' => 'page_default',
        'access callback' => TRUE,
        'type' => MENU_CALLBACK,
    );
	//Category link
	$listCategory = DataCommon::getListCategoryFull('notsort');
	foreach($listCategory as $key => $val){
		//Category
		$key_cat = $val['category_name_alias'].'-'.$val['category_id'].'.html';
		$items[$key_cat] = array(
			"title" => $val['category_name'],
			"description" => $val['category_name'],
			'page callback' => 'menuLoad',
			'page arguments' => array('SiteController/getMenuLoad'),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);
		//Detail
		$key_detail = $val['category_name_alias'];
		$items[$key_detail.'/%'] = array(
			"title" => $val['category_name'],
			"description" => $val['category_name'],
			'page callback' => 'menuLoad',
			'page arguments' => array('SiteController/getMenuLoad'),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);
	}
	$items['print/%/%'] = array(
			"title" => 'In bài viết',
			"description" => 'In bài viết',
			'page callback' => 'menuLoad',
			'page arguments' => array('SiteController/getItemPrint'),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);

	$items['tim-kiem.html'] = array(
			"title" => 'Tìm kiếm',
			"description" => 'Tìm kiếm',
			'page callback' => 'menuLoad',
			'page arguments' => array('SiteController/getItemSearh'),
			'access callback' => TRUE,
			'type' => MENU_CALLBACK,
		);
  return $items;
}

function Site_block_info() {
	$blocks['block-header'] = array(
		'info' => t('Block header'),
		'status'	=> TRUE,
		'region'	=> 'header',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-slide'] = array(
		'info' => t('Block slide'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-content'] = array(
		'info' => t('Block content'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-footer'] = array(
		'info' => t('Block footer'),
		'status'	=> TRUE,
		'region'	=> 'footer',
		'weight'	=> 0,
		'visibility' => 1,
	);

	//Left
	$blocks['block-left-category'] = array(
		'info' => t('Block left category'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-left-services-focus'] = array(
		'info' => t('Block left services focus'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-left-banner'] = array(
		'info' => t('Block left banner'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-left-images'] = array(
		'info' => t('Block left images'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-left-document'] = array(
		'info' => t('Block left document'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-left-video'] = array(
		'info' => t('Block left video'),
		'status'	=> TRUE,
		'region'	=> 'left',
		'weight'	=> 0,
		'visibility' => 1,
	);
	//Right
	$blocks['block-right-video'] = array(
		'info' => t('Block right video'),
		'status'	=> TRUE,
		'region'	=> 'right',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-right-document'] = array(
		'info' => t('Block right document'),
		'status'	=> TRUE,
		'region'	=> 'right',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-right-images'] = array(
		'info' => t('Block right images'),
		'status'	=> TRUE,
		'region'	=> 'right',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-right-banner'] = array(
		'info' => t('Block right banner'),
		'status'	=> TRUE,
		'region'	=> 'right',
		'weight'	=> 0,
		'visibility' => 1,
	);
	$blocks['block-fixed-banner-screen'] = array(
		'info' => t('Block fixed banner screen'),
		'status'	=> TRUE,
		'region'	=> 'content',
		'weight'	=> 0,
		'visibility' => 1,
	);

   return $blocks;
}
function Site_theme() {
	return array(
	    'block-header' => array(
	      'template' => 'View/tpl/block-header'
	    ),
	    'block-slide' => array(
	      'template' => 'View/tpl/block-slide'
	    ),
	    'block-content' => array(
	      'template' => 'View/tpl/block-content'
	    ),
		'block-footer' => array(
	      'template' => 'View/tpl/block-footer'
	    ),
	   	
	   	//Left 
		'block-left-category' => array(
	      'template' => 'View/tpl/block-left-category'
	    ),
	    'block-left-services-focus' => array(
	      'template' => 'View/tpl/block-left-services-focus'
	    ),
	    'block-left-banner' => array(
	      'template' => 'View/tpl/block-left-banner'
	    ),
	    //Right
	    'block-right-video' => array(
	      'template' => 'View/tpl/block-right-video'
	    ),
	    'block-right-document' => array(
	      'template' => 'View/tpl/block-right-document'
	    ),
	    'block-right-images' => array(
	      'template' => 'View/tpl/block-right-images'
	    ),
	    'block-right-banner' => array(
	      'template' => 'View/tpl/block-right-banner'
	    ),
	    //fix banner screen
	    'block-fixed-banner-screen' => array(
	      'template' => 'View/tpl/block-fixed-banner-screen'
	    ),

	    'pageNews' => array(
	      'template' => 'View/tpl/pageNews'
	    ),
	    'pageNewsDetail' => array(
	      'template' => 'View/tpl/pageNewsDetail'
	    ), 
	    'pageNewsSearch' => array(
	      'template' => 'View/tpl/pageNewsSearch'
	    ),

	    'pageVideo' => array(
	      'template' => 'View/tpl/pageVideo'
	    ),
	    'pageVideoDetail' => array(
	      'template' => 'View/tpl/pageVideoDetail'
	    ),
	    'pageVideoSearch' => array(
	      'template' => 'View/tpl/pageVideoSearch'
	    ),

	    'pageImage' => array(
	      'template' => 'View/tpl/pageImage'
	    ),
	    'pageImageDetail' => array(
	      'template' => 'View/tpl/pageImageDetail'
	    ),
	    
	    'pageServicesFocus' => array(
	      'template' => 'View/tpl/pageServicesFocus'
	    ),
	    'pageServicesFocusDetail' => array(
	      'template' => 'View/tpl/pageServicesFocusDetail'
	    ),
	);
}
function Site_block_view($delta='') {
	$block = array();
	switch ($delta) {
		case 'block-header':
		  $block['subject'] = t('Block header');
		  $block['content'] = block_header();
		  break;
		 case 'block-slide':
		  $block['subject'] = t('Block slide');
		  $block['content'] = block_slide();
		  break;
		case 'block-content':
		  $block['subject'] = t('Block content');
		  $block['content'] = block_content();
		  break;
		case 'block-footer':
		  $block['subject'] = t('Block footer');
		  $block['content'] = block_footer();
		  break;
		case 'block-fixed-banner-screen':
		  $block['subject'] = t('Block fixed banner screen');
		  $block['content'] = block_fixed_banner_screen();
		  break;
		//Left
		case 'block-left-category':
		  $block['subject'] = t('Block left category');
		  $block['content'] = block_left_category();
		  break;
		case 'block-left-services-focus':
		  $block['subject'] = t('Block left services focus');
		  $block['content'] = block_left_services_focus();
		  break;
		case 'block-left-banner':
		  $block['subject'] = t('Block left banner');
		  $block['content'] = block_left_banner();
		  break;
		case 'block-left-images':
		  $block['subject'] = t('Block left images');
		  $block['content'] = block_left_images();
		  break;
		case 'block-left-document':
		  $block['subject'] = t('Block left document');
		  $block['content'] = block_left_document();
		  break;
		case 'block-left-video':
		  $block['subject'] = t('Block left video');
		  $block['content'] = block_left_video();
		  break;
		//Right
		case 'block-right-video':
		  $block['subject'] = t('Block right video');
		  $block['content'] = block_right_video();
		  break;
		case 'block-right-document':
		  $block['subject'] = t('Block right document');
		  $block['content'] = block_right_document();
		  break;
		case 'block-right-images':
		  $block['subject'] = t('Block right images');
		  $block['content'] = block_right_images();
		  break;
		case 'block-right-banner':
		  $block['subject'] = t('Block right banner');
		  $block['content'] = block_right_banner();
		  break; 
	}
	return $block;
}
function Site_init() {
	$uri = request_uri();
	if(preg_match("/admin/", $uri) == 0){
		$files = array(
			'Model/Site.php',
			'Controller/SiteController.php',

			'View/js/site.js',
			'View/css/site.css',
		);
		Loader::load('Site', $files);
		$files = array(
	        'css/core.css',
	        'js/jquery.alerts.js',
	    );
	    Loader::load('Core', $files);
	}
	FunctionLib::sessionLang();
}

function page_default(){
	global $base_url;
    drupal_set_title('Trang chủ');
    $meta_seo = Utility::keyword_seo($keyword='SITE_SEO_HOME');
    if(count($meta_seo)>0){
        foreach($meta_seo as $v){
            $meta_title = $v->meta_title;
            $meta_keywords  = $v->meta_keywords;
            $meta_description = $v->meta_description;
            if($v->img != ''){
                $img = $base_url.'/uploads/images/info/'.$v->img;
            }else{
                 $img = '';
            }
        }
    }else{
            $meta_title = 'Home';
            $meta_keywords = 'Home';
            $meta_description = 'Home';
            $img = '';
    }
    SeoMeta::SEO($meta_title, $img, $meta_title, $meta_keywords, $meta_description);

	return '';
}

function block_header(){
	$listCategory = DataCommon::getListCategoryFull('sort');
	return theme('block-header', array('listCategory'=>$listCategory));
}
function block_slide(){
	$arrSliderPost = SiteController::getListPostSlider();
	$contentBanner = SiteController::blockContentHomeBanner();
	return theme('block-slide', array('contentBanner'=>$contentBanner, 'arrSliderPost'=>$arrSliderPost));
}

function block_content(){
	$listCategory = DataCommon::getListCategoryFull('sort');
	return theme('block-content', array('listCategory'=>$listCategory));
}
function block_footer(){
	
	return theme('block-footer');
}
function block_fixed_banner_screen(){
	
	$leftBanner = SiteController::blockLeftWebBanner();
	$rightBanner = SiteController::blockRightWebBanner();

	$data = array(
			'leftBanner'=>$leftBanner,
			'rightBanner'=>$rightBanner,
			);

	return theme('block-fixed-banner-screen', $data);
}
//Left
function block_left_category(){
	$listCategory = DataCommon::getListCategoryFull('sort');
	return theme('block-left-category', array('listCategory'=>$listCategory));
}
function block_left_services_focus(){

	return theme('block-left-services-focus');
}
function block_left_banner(){
	$leftBanner = SiteController::blockLeftBanner();
	return theme('block-left-banner', array('leftBanner'=>$leftBanner));
}
function block_left_images(){
	$listImageHot = SiteController::blockRightImage();
	return theme('block-right-images', array('listImageHot'=>$listImageHot));
}
function block_left_document(){
	$listCategory = DataCommon::getListCategoryFull('sort');
	return theme('block-right-document', array('listCategory'=>$listCategory));
}
function block_left_video(){
	$listVideoHot = SiteController::blockRightVideo();
	return theme('block-right-video', array('listVideoHot'=>$listVideoHot));
}
//Right
function block_right_video(){
	$listVideoHot = SiteController::blockRightVideo();
	return theme('block-right-video', array('listVideoHot'=>$listVideoHot));
}
function block_right_document(){
	$listCategory = DataCommon::getListCategoryFull('sort');
	return theme('block-right-document', array('listCategory'=>$listCategory));
}
function block_right_images(){
	$listImageHot = SiteController::blockRightImage();
	return theme('block-right-images', array('listImageHot'=>$listImageHot));
}
function block_right_banner(){
	$rightBanner = SiteController::blockRightBanner();
	return theme('block-right-banner', array('rightBanner'=>$rightBanner));
}